guest_list = [
    'Kali',
    'Ice Dospeec',
    'Adi',
    'Ice Sofianec',
    'Jore',
    'Mia',
    'Jefri',
    'Tsveti',
    'Pesho',
    'Misho',
    'Kosara',
    'Sando',
    'Lili',
    'Kalata',
    'Yoana',
    'Rade',
    'Veso',
    'Eliza',
    'Veronika',
    'Maison',
    'Lelq Maria',
    'Kalin',
    'Na Kalin gadjeto',
    'Samuil',
    'Ivo',
    'Kamila',
    'Baba S',
    'Baba V',
    'Borkata',
    'Na Borkata jena mu',
    'Vasketo',
    'Na Vasketo  priqtelkata',
    'Gs05',
    'Boev',
    'Na Boev jena mu',
    'Misheto',
    'Iliq',
    'Dani chaev',
    'Na Dani jena mu',
    'Mama',
    'Tate',
    'Tumbe',
    'Sasho',
    'Gogi',
    'Kristina',
    'Zahata',
    'Lelq Vencheto',
    'Chicho Stoqn',
    'Vasko B',
    
]

print(len(guest_list))

